# Generated by Django 3.1.5 on 2024-11-03 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_course_techer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='techer',
            new_name='teacher',
        ),
    ]
